name: Run test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bun-actions/setup-bun@v1
      - run: bun install
      - run: bun test
